name: Clean Arch Node API - Deployment

on:
  pull_request:
    branches: [main]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [18x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      
      - name: Run Tests
        run: yarn test
      
      - name: Run Coverage
        run : yarn test:cov
      
      - name: Coveralls
        uses: coverallsapp/github-action@v1
  
  continuous-delivery:
    runs-on: ubuntu-latest

    needs: [continuous-integration]

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          buildpack: 'https://github.com/zidizei/heroku-buildpack-tsc#v2.0'