name: Clean Arch Node API - Deployment

on:
  pull_request:
    branches: [main]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [18x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      
      - name: Run Tests
        run: yarn test
      
      - name: Run Coverage
        run : yarn test:cov
      
      - name: Coveralls
        uses: coverallsapp/github-action@v1